Simplificando o script para geração local git-producao-local #22
Imprime mensagem se não encontra o arquivo para abrir #22

diff --git a/git-scripts/git-producao-local-open-pdf b/git-scripts/git-producao-local-open-pdf
--- a/git-scripts/git-producao-local-open-pdf
+++ b/git-scripts/git-producao-local-open-pdf
@@ -21,4 +21,8 @@ then
 fi
 
 
-
+if ! [ -f $TEST_PDF ] && ! [ -f $LIVRO_PDF ]
+then
+  echo "Cannot find at $TEST_PDF or $LIVRO_PDF at $REPOSITORIO_PATH"
+  echo "Try run: git producao-local -b"
+fi
